from setuptools import setup, find_packages

setup(
    name='mama',
    version='0.0.1',
    description='Mama Django project.',
    long_description = open('README.rst', 'r').read() + open('AUTHORS.rst', 'r').read() + open('CHANGELOG.rst', 'r').read(),
    author='Praekelt Foundation',
    author_email='dev@praekelt.com',
    license='BSD',
    url='http://github.com/praekelt/mama',
    packages = find_packages(),
    dependency_links = [
    ],
    install_requires=[
        'django>=1.4',
        'django-generate',
        'django-haystack',
        'django-moderator',
        'django-preferences',
        'django-sites-groups',
        'django-snippetscream',
        'django-userprofile',
        'flup',
        'jmbo',
        'jmbo-poll',
        'jmbo-post',
        'psycopg2',
        'python-ambient',
        'south',
        'whoosh',
    ],
    tests_require=[
        'django-setuptest',
    ],
    test_suite="setuptest.SetupTestSuite",
    include_package_data=True,
    classifiers = [
        "Programming Language :: Python",
        "License :: OSI Approved :: BSD License",
        "Development Status :: 4 - Beta",
        "Operating System :: OS Independent",
        "Framework :: Django",
        "Intended Audience :: Developers",
        "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    ],
    zip_safe=False,
)
